apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  namespace: crawlab
  labels:
    type: local
spec:
  storageClassName: csi-cephfs-sc
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/mongodb/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: crawlab
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi